import type { Metadata } from 'next';
import './globals.css';
import { AppProvider } from '@/providers/AppProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { Web3AuthContextProvider } from '@/providers/Web3AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Web3AuthContextProvider>
            <AppProvider>{children}</AppProvider>
          </Web3AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
